### DELETE a Item to the Catalog collection

curl --request DELETE \
    --url http://localhost:5250/catalog/6 \
    --header 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkV0STM0ajhSa0VqQjVOZXpYR1pqdSJ9.eyJpc3MiOiJodHRwczovL2Rldi1qM2FrbHdmb3c4MDZvb3QwLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJWSnpqSU10ZmV2T1BMajBMcllaelh6b0R4MEhzMURhRkBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9oaXJhZDIzLWFwaSIsImlhdCI6MTc0NTUzNDAyNywiZXhwIjoxNzQ1NjIwNDI3LCJzY29wZSI6ImRlbGV0ZTpjYXRhbG9nIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIiwiYXpwIjoiVkp6aklNdGZldk9QTGowTHJZWnpYem9EeDBIczFEYUYifQ.iPeYP2NRacnV-aQlIr3ueP22uMU_fwq3bB7sSYPwteZoVoGrT3HQyyUngMTmtG6FWmBkFjvKyz4AOXOI2Z8nZGaz6Fa13BBnULlLVgr3cRY3jdCGPQSnnQIAk5efAtOQyWusB36ZVtK5lXGDNUhqHRwV-MaXmVqfjIqWf0NmWtHHc-X5LKC9GwY4Jd05Rn4SWh-9wQ7xugd6SN1wTwFXs2MjQZ0bRE5JDtJyjLuu9cmRzT-IYFwIOeMI9sotGU6z9LIa20dfZX1S4L6hFZOqWjgqXKHs9-tAV62xlUgVrqguhr7Iq976uZLP7XH7b1x4vLBdRLYhaYaqR15QKXszpw'